---
- name: Configurar resolv.conf e /etc/hosts
  hosts: all
  become: true
  tasks:
    - name: Configurar /etc/resolv.conf
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 127.0.0.53
          options edns0 trust-ad
          search maestriatec.local
      notify:
        - Restart Network Service

    - name: Configurar /etc/hosts
      copy:
        dest: /etc/hosts
        content: |
          127.0.0.1 localhost
          192.168.18.100 awx.sysadmin.local awx
          192.168.18.41 debian
          192.168.18.45 rocky
          192.168.18.48 terraform
          192.168.18.49 winsserveraddc.maestriatec.local winsserveraddc
          192.168.18.50 proxmox
      notify:
        - Restart Network Service

  handlers:
    - name: Restart Network Service
      block:
        - name: Check if NetworkManager exists
          command: systemctl is-active NetworkManager
          register: network_manager_status
          ignore_errors: true

        - name: Restart NetworkManager (AlmaLinux, Rocky, CentOS)
          systemd:
            name: NetworkManager
            state: restarted
          when: network_manager_status.rc == 0

        - name: Restart networking service (Debian/Ubuntu)
          systemd:
            name: networking
            state: restarted
          when: network_manager_status.rc != 0

        - name: Restart systemd-networkd (if used)
          systemd:
            name: systemd-networkd
            state: restarted
          when: network_manager_status.rc != 0
...
