---
- name: Configurar resolv.conf e /etc/hosts
  hosts: all
  tasks:
    - name: Configurar /etc/resolv.conf
      copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 192.168.18.49
          options edns0 trust-ad
          search maestriatec.local
      notify:
        - Restart NetworkManager

    - name: Configurar /etc/hosts
      copy:
        dest: /etc/hosts
        content: |
          127.0.0.1 localhost
          192.168.18.100 awx.sysadmin.local awx
          192.168.18.41 debian
          192.168.18.44 rocky
          192.168.18.45 alma
          192.168.18.48 terraform
          192.168.18.49 winsserveraddc.maestriatec.local winsserveraddc
      notify:
        - Restart NetworkManager

  handlers:
    - name: Restart NetworkManager
      service:
        name: NetworkManager
        state: restarted
...
