---
- name: Install packages
  hosts: all
  tasks:
    - name: APT | Install packages
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
...
